

## Challenge: #TidyTuesday 2023 week 29
## Data:      GPT detectors
## Author:    Steven Ponce
## Date:      2023-07-17


#' NOTES:
#' But what are GPT detectors, and why are they used in content writing?
#'
#' GPT detectors are algorithms that use artificial intelligence to analyze and evaluate content. 
#' They are designed to identify content that has been generated by a machine learning model, 
#' such as a language model like GPT-3.
#' https://servicelifter.com/guides/how-to-avoid-being-flagged-by-gpt-detectors-the-expert-strategies-for-content-writers/#:~:text=But%20what%20are%20GPT%20detectors,language%20model%20like%20GPT%2D3.


## 1. LOAD PACKAGES & SETUP ----  
pacman::p_load(tidyverse, tidytuesdayR, ggtext, showtext, janitor, camcorder, scales, lubridate)
 

# |- figure size ---- 
gg_record(
    dir    = here::here("temp_plots"), 
    device = "png",
    width  = 6,
    height = 8,
    units  = "in",
    dpi    = 600) 

# |- resolution ---- 
showtext_opts(dpi = 600)


## 2. READ IN THE DATA ----
tt <- tidytuesdayR::tt_load(2023, week = 29) 

detectors <- tt$detectors %>% clean_names()

readme(tt)   
rm(tt)   


## 3. EXAMINING THE DATA ----
glimpse(detectors)  
colnames(detectors)

detectors %>% count(kind, sort = T)
detectors %>% count(pred_ai, sort = T)
detectors %>% count(pred_class, sort = T)
detectors %>% count(detector, sort = T)           
detectors %>% count(native, sort = T)          
detectors %>% count(name, sort = T)            
detectors %>% count(model, sort = T)            
detectors %>% count(prompt, sort = T)


## 4. TIDYDATA ---- 

# |- plot data ----
data_plot <- detectors %>% 
    # rename cols
    rename(type = kind,
           pred = pred_ai,
           classification = pred_class) %>%
    
    # summary
    filter(!is.na(native)) %>% 
    group_by(detector, native) %>% 
    summarise(mean_accuracy = mean(type == classification),
              .groups = "drop") %>% 
    
    # pivot wider
    pivot_wider(
        names_from  = native,
        values_from = mean_accuracy,
    ) %>% 
    rename(no = No, yes = Yes) %>% 
   
     # factors, descending
    mutate(detector = fct_reorder(detector, no, .desc = TRUE)) %>% 
    
    # point labels
    mutate(
        label_no  = paste0(round((no * 100), 1), "%"),
        label_yes = paste0(round((yes * 100), 1), "%"),
    )



# 5. VISUALIZATION ---- 

### |- plot aesthetics ---- 
bkg_col      <- "#666a86"      
title_col    <- "#FAFAFA"          
subtitle_col <- "#FAFAFA"   
caption_col  <- "#FAFAFA" 
text_col     <- "#FAFAFA"   

col_palette <- list("no" = "#edafb8" , "yes" = "#e8ddb5") 


### |-  titles and caption ----
tt <- str_glue("#TidyTuesday: 2023 Week 29 &bull; Source: GPT detectors R package<br>")  
tw <- str_glue("<span style='font-family:fa6-brands'>&#xf099;</span>")
gh <- str_glue("<span style='font-family:fa6-brands'>&#xf09b;</span>")
mn <- str_glue("<span style='font-family:fa6-brands'>&#xf4f6;</span>")

title_text    <- str_glue("GPT Detectors: how accurate they are?") 

no  <- str_glue("<span style='font-size:22pt; color: #edafb8'>**Non-Native**</span>")
yes <- str_glue("<span style='font-size:22pt; color: #e8ddb5'>**Native**</span>")

subtitle_text <- str_glue("{no} vs. {yes} English Speaker") 

caption_text  <- str_glue("{tt} Visualization: {tw} @sponce1 &bull; {mn} @sponce1(graphic.social) Code: {gh} poncest &bull; Tools: #rstats #ggplot")


### |-  fonts ----
font_add('fa6-brands', 'fonts/fa6-brands-regular-400.otf')
font_add_google("VT323", family = "title")                        
font_add_google("VT323", family = "subtitle")            
font_add_google("Share Tech Mono", family = "text")  
font_add_google("PT Sans Narrow", family = "caption")
showtext_auto(enable = TRUE)     


### |-  final plot ----
ggplot(data = data_plot) + 
    
    # geoms
    geom_segment(aes(x = detector, xend = detector, y = no, yend = yes),
                 color = 'gray', size = 0.5)+
    
    geom_point(aes(x = detector, y = no), size = 4, color = col_palette[1]) + 
    geom_point(aes(x = detector, y = yes), size = 4, color = col_palette[2]) + 
    
    # point labels
    geom_text(aes(x = detector, y = no, label = label_no),
              color = col_palette[1], size = 4, hjust   = 0.5,
              family = 'text', nudge_x = 0.3) + 
    
    geom_text(aes(x = detector, y = yes, label = label_yes),
              color = col_palette[2], size = 4, hjust   = 0.5,
              family = 'text', nudge_x = 0.3) + 
    
    # scales
    scale_x_discrete()+
    
    scale_y_continuous(breaks = seq(0.2, 1, by = .2),
                       limits = c(0.2, 1),
                       expand = c(0.05, 0.05),
                       label  = percent) +
    
    coord_flip(clip = "off", expand = TRUE)+
    
    # labs
    labs(x = "", y = "Mean Accuracy",
         title    = title_text,
         subtitle = subtitle_text,
         caption  = caption_text) +
    
    # themes
    theme_minimal()+
    theme(
        plot.title.position   = "plot",
        plot.caption.position = "plot",
        legend.position       = 'plot',
        
        plot.background     = element_rect(fill = bkg_col, color = bkg_col),
        panel.background    = element_rect(fill = bkg_col, color = bkg_col),
        
        plot.margin         = margin(t = 10, r = 15, b = 10, l = 15),
        
        axis.title.x        = element_text(size = 14, face = 'bold', color = text_col, 
                                           family = 'text', margin = margin(t = 10)), 
        axis.text           = element_text(size = 12, color = text_col, family = 'text'),
        axis.line.x         = element_line(color = text_col),
        
        axis.title.y        = element_blank(),
        
        panel.grid          = element_blank(),

        plot.title          = element_markdown(
            family          = 'title',
            color           = title_col,
            face            = "bold",
            size            = 26,  
            margin          = margin(t = 10, b = 5)),
        
        plot.subtitle       = element_markdown(
            family          = 'subtitle',
            color           = title_col,
            lineheight      = 0.8, 
            size            = 20,  
            margin          = margin(t = 5, b = 10)),
        
        plot.caption        = element_markdown(
            family          = 'caption',
            color           = caption_col,
            lineheight      = 0.6,
            size            = 10,
            hjust           = 0.5,
            halign          = 0.5,
            margin          = margin(t = 10, b = 10)),
        
    )



sessioninfo::session_info(include_base = TRUE) 
## 6. SESSION INFO ---- 
# ─ Session info ─────────────────────────────────────────────────────────
# setting  value
# version  R version 4.3.1 (2023-06-16 ucrt)
# os       Windows 10 x64 (build 19044)
# system   x86_64, mingw32
# ui       RStudio
# language (EN)
# collate  English_United States.utf8
# ctype    English_United States.utf8
# tz       America/New_York
# date     2023-07-21
# rstudio  2023.06.1+524 Mountain Hydrangea (desktop)
# pandoc   NA
# 
# ─ Packages ─────────────────────────────────────────────────────────────
# package      * version date (UTC) lib source
# base         * 4.3.1   2023-06-16 [2] local
# bit            4.0.5   2022-11-15 [1] CRAN (R 4.3.0)
# bit64          4.0.5   2020-08-30 [1] CRAN (R 4.3.0)
# camcorder    * 0.1.0   2022-10-03 [1] CRAN (R 4.3.0)
# cellranger     1.1.0   2016-07-27 [1] CRAN (R 4.3.0)
# cli            3.6.1   2023-03-23 [1] CRAN (R 4.3.0)
# colorspace     2.1-0   2023-01-23 [1] CRAN (R 4.3.0)
# commonmark     1.9.0   2023-03-17 [1] CRAN (R 4.3.0)
# compiler       4.3.1   2023-06-16 [2] local
# crayon         1.5.2   2022-09-29 [1] CRAN (R 4.3.0)
# curl           5.0.0   2023-01-12 [1] CRAN (R 4.3.0)
# datasets     * 4.3.1   2023-06-16 [2] local
# dplyr        * 1.1.2   2023-04-20 [1] CRAN (R 4.3.0)
# fansi          1.0.4   2023-01-22 [1] CRAN (R 4.3.0)
# farver         2.1.1   2022-07-06 [1] CRAN (R 4.3.0)
# forcats      * 1.0.0   2023-01-29 [1] CRAN (R 4.3.0)
# fs             1.6.2   2023-04-25 [1] CRAN (R 4.3.0)
# generics       0.1.3   2022-07-05 [1] CRAN (R 4.3.0)
# ggplot2      * 3.4.2   2023-04-03 [1] CRAN (R 4.3.0)
# ggtext       * 0.1.2   2022-09-16 [1] CRAN (R 4.3.0)
# gifski         1.12.0  2023-05-19 [1] CRAN (R 4.3.0)
# glue           1.6.2   2022-02-24 [1] CRAN (R 4.3.0)
# graphics     * 4.3.1   2023-06-16 [2] local
# grDevices    * 4.3.1   2023-06-16 [2] local
# grid           4.3.1   2023-06-16 [2] local
# gridtext       0.1.5   2022-09-16 [1] CRAN (R 4.3.0)
# gtable         0.3.3   2023-03-21 [1] CRAN (R 4.3.0)
# here           1.0.1   2020-12-13 [1] CRAN (R 4.3.0)
# hms            1.1.3   2023-03-21 [1] CRAN (R 4.3.0)
# httr           1.4.6   2023-05-08 [1] CRAN (R 4.3.0)
# janitor      * 2.2.0   2023-02-02 [1] CRAN (R 4.3.0)
# jsonlite       1.8.5   2023-06-05 [1] CRAN (R 4.3.0)
# lifecycle      1.0.3   2022-10-07 [1] CRAN (R 4.3.0)
# lubridate    * 1.9.2   2023-02-10 [1] CRAN (R 4.3.0)
# magick         2.7.4   2023-03-09 [1] CRAN (R 4.3.0)
# magrittr       2.0.3   2022-03-30 [1] CRAN (R 4.3.0)
# markdown       1.7     2023-05-16 [1] CRAN (R 4.3.0)
# methods      * 4.3.1   2023-06-16 [2] local
# munsell        0.5.0   2018-06-12 [1] CRAN (R 4.3.0)
# pacman         0.5.1   2019-03-11 [1] CRAN (R 4.3.0)
# parallel       4.3.1   2023-06-16 [2] local
# pillar         1.9.0   2023-03-22 [1] CRAN (R 4.3.0)
# pkgconfig      2.0.3   2019-09-22 [1] CRAN (R 4.3.0)
# purrr        * 1.0.1   2023-01-10 [1] CRAN (R 4.3.0)
# R6             2.5.1   2021-08-19 [1] CRAN (R 4.3.0)
# ragg           1.2.5   2023-01-12 [1] CRAN (R 4.3.0)
# Rcpp           1.0.10  2023-01-22 [1] CRAN (R 4.3.0)
# readr        * 2.1.4   2023-02-10 [1] CRAN (R 4.3.0)
# readxl         1.4.2   2023-02-09 [1] CRAN (R 4.3.0)
# rlang          1.1.1   2023-04-28 [1] CRAN (R 4.3.0)
# rprojroot      2.0.3   2022-04-02 [1] CRAN (R 4.3.0)
# rstudioapi     0.14    2022-08-22 [1] CRAN (R 4.3.0)
# rsvg           2.4.0   2022-11-21 [1] CRAN (R 4.3.0)
# rvest          1.0.3   2022-08-19 [1] CRAN (R 4.3.0)
# scales       * 1.2.1   2022-08-20 [1] CRAN (R 4.3.0)
# selectr        0.4-2   2019-11-20 [1] CRAN (R 4.3.0)
# sessioninfo    1.2.2   2021-12-06 [1] CRAN (R 4.3.0)
# showtext     * 0.9-6   2023-05-03 [1] CRAN (R 4.3.0)
# showtextdb   * 3.0     2020-06-04 [1] CRAN (R 4.3.0)
# snakecase      0.11.0  2019-05-25 [1] CRAN (R 4.3.0)
# stats        * 4.3.1   2023-06-16 [2] local
# stringi        1.7.12  2023-01-11 [1] CRAN (R 4.3.0)
# stringr      * 1.5.0   2022-12-02 [1] CRAN (R 4.3.0)
# svglite        2.1.1   2023-01-10 [1] CRAN (R 4.3.0)
# sysfonts     * 0.8.8   2022-03-13 [1] CRAN (R 4.3.0)
# systemfonts    1.0.4   2022-02-11 [1] CRAN (R 4.3.0)
# textshaping    0.3.6   2021-10-13 [1] CRAN (R 4.3.0)
# tibble       * 3.2.1   2023-03-20 [1] CRAN (R 4.3.0)
# tidyr        * 1.3.0   2023-01-24 [1] CRAN (R 4.3.0)
# tidyselect     1.2.0   2022-10-10 [1] CRAN (R 4.3.0)
# tidytuesdayR * 1.0.2   2022-02-01 [1] CRAN (R 4.3.0)
# tidyverse    * 2.0.0   2023-02-22 [1] CRAN (R 4.3.0)
# timechange     0.2.0   2023-01-11 [1] CRAN (R 4.3.0)
# tools          4.3.1   2023-06-16 [2] local
# tzdb           0.4.0   2023-05-12 [1] CRAN (R 4.3.0)
# usethis        2.2.0   2023-06-06 [1] CRAN (R 4.3.0)
# utf8           1.2.3   2023-01-31 [1] CRAN (R 4.3.0)
# utils        * 4.3.1   2023-06-16 [2] local
# vctrs          0.6.2   2023-04-19 [1] CRAN (R 4.3.0)
# vroom          1.6.3   2023-04-28 [1] CRAN (R 4.3.0)
# withr          2.5.0   2022-03-03 [1] CRAN (R 4.3.0)
# xfun           0.39    2023-04-20 [1] CRAN (R 4.3.0)
# xml2           1.3.4   2023-04-27 [1] CRAN (R 4.3.0)
# 
# [1] C:/Users/poncest/AppData/Local/R/win-library/4.3
# [2] C:/Users/poncest/AppData/Local/Programs/R/R-4.3.1/library
# 
# ────────────────────────────────────────────────────────────────────────
# > 

  