
## Challenge: #TidyTuesday 2022 week 18
## Author: Steven Ponce
## Date: 2022-05-03
 
## 1. Load packages ----
library(pacman)
p_load(tidyverse, tidytuesdayR, ggtext, showtext, janitor, skimr)


## 2. Read in the data ----
tt <- tidytuesdayR::tt_load(2022, week = 18)

wind <- tt$wind %>% clean_names()
solar <- tt$solar %>% clean_names()
# rm(tt)


## 3. Examine the data ----

glimpse(solar)
range(solar$date)

glimpse(wind)
range(wind$date)


## 4. Tidydata ----

# combining the data together (full joint)
combined_data <-  wind %>% 
    full_join(y = solar)  %>% 
    
    # select specific columns
    select(date, wind_mwh, solar_mwh) %>% 
    
    # rename columns
    rename(wind = wind_mwh,
           solar = solar_mwh) %>% 
    
    # pivot longer and drop NAs
    pivot_longer(cols = !date, names_to = 'energy_type', values_to = 'projected_price') %>% 
    drop_na()


## 5. Visualization ----

# base plot 
g <- combined_data %>% 
    ggplot(aes(x = date,
               y = projected_price,
               color = energy_type)) +
    
    geom_point(size = 4, alpha = 0.85)+
    geom_smooth(method = 'loess', se = FALSE) 

g

# customization

# colors
col_1      <- '#ad7e17'  #yellow 
col_2      <- '#4b2680'  #purple
bkg_col    <- '#a5d7f2'     
title_col  <- '#091724' 

# google fonts

font_add_google(family="Bangers", "Bangers")                  # title
font_add_google(family="Farsan", "Farsan")                    # subtitle
font_add_google(family="Metal", "Metal")                      # text

font_add_google(family='Saira Semi Condensed', 'Saira Semi Condensed')  # caption
showtext_auto(enable = TRUE) 



# final plot
g +
    
    # scales
    scale_y_continuous(breaks = seq(0, 350, by = 50),
                       limits = c(0, 350),
                       expand = c(0.05, 0.05)) +
    
    scale_x_date(breaks = '2 year', date_labels = "%Y") +
    
    # change color
    scale_color_manual(values = c(col_1, col_2)) +
    
    coord_cartesian(clip = 'off', expand = FALSE) +
    
    # labs
     labs(
        title = "Power Purchase Agreement (PPA) Projected Price <br> in Megawatt hour for <span style='font-size:70pt; color:#ad7e17'>**Solar**</span> & <span style='font-size:70pt; color:#4b2680'>**Wind**</span>",
        subtitle = "A power purchase agreement (PPA) is a contractual agreement between energy buyers and sellers. They come together and agree to buy and sell an amount of energy \nwhich is or will be generated by a renewable asset. PPAs are usually signed for a long-term period between 10-20 years.",
        caption = paste0(
            "#TidyTuesday: 2022 Week 18\n",
            "Source: Berkeley Lab\n",
            "Visualization: Steven Ponce (@sponce1)"), 
        x = '', 
        y = '') +
    
    # theme
    theme_minimal(base_family = 'Metal') +
    theme(
        plot.title.position   = "plot",
        plot.caption.position = "plot",
        legend.position       = 'plot',
        
        axis.text             = element_text(size = 22), 
        axis.title            = element_blank(),                    
        
        panel.grid.minor      = element_blank(),
        panel.grid.major.x    = element_blank(),
        panel.grid.major.y    = element_line(linetype = "dotted", size = 1, color = 'gray'),
        
        plot.background       = element_rect(fill = bkg_col, color = bkg_col),
        panel.background      = element_rect(fill = bkg_col, color = bkg_col),
     
        plot.margin           = margin(t = 30, r = 40, b = 30, l = 40),
        
        plot.title    = element_markdown(
            family    = 'Bangers',
            color     = title_col,
            face      = "bold",
            size      = 70,  
            margin    = margin(t = 10)),
        
        plot.subtitle = element_text(
            family    = 'Farsan',
            color     = title_col,
            #face      = "italic",
            size      = 23,
            margin    = margin(t = 25, b = 40)),
            
        plot.caption  = element_text(
            family    = 'Saira Semi Condensed',
            color     = '#808080', 
            size      = 12,
            hjust     = 0.98,
            margin    = margin(t = 20, b = 10)),
    ) 
    


# resolution
showtext_opts(dpi = 300) 
     

## 6. Save final figure ----
ggsave('2022/Week_18/2022_18_capacity.png',
       width = 20, height = 11, units = 'in',  dpi = 300)


showtext_auto(FALSE)

